# Generated by Django 4.2.3 on 2023-07-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.PositiveIntegerField(max_length=10)),
                ('passing_school', models.PositiveSmallIntegerField(verbose_name='Year of Passing School')),
                ('attend_reunion', models.BooleanField()),
                ('members_attending_event', models.PositiveSmallIntegerField(max_length=2, verbose_name='Members Attending The Event')),
                ('event', models.CharField(choices=[('1', 'Life Time Membership INR 2000'), ('2', 'Ex Bhavanites Reunion INR 7000'), ('3', 'Guest Attending Reunion INR 5000'), ('4', 'Guest Attending 1st Day Full Fuction INR 3500'), ('5', 'Guest Attending 2nd Day Fuction INR 1500'), ('6', 'Guest Attending only Gala Dinner INR 2000')], max_length=1)),
                ('attendees_names', models.CharField(max_length=255)),
                ('payment_date', models.DateField()),
                ('payment_amount', models.PositiveIntegerField()),
                ('payment_transaction_id', models.CharField(max_length=100)),
                ('shirt_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], max_length=50, verbose_name='T-shirt Size')),
                ('firm_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Firm if Any')),
            ],
        ),
    ]
