# Generated by Django 4.2.3 on 2023-07-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='members_attending_event',
            field=models.PositiveSmallIntegerField(verbose_name='Members Attending The Event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
    ]
