# Generated by Django 4.2.3 on 2023-07-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_registration_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.CharField(choices=[('lifetime_membership', 'Life Time Membership (INR 2000)'), ('ex_bhavanites_reunion', 'Ex Bhavanites Reunion (INR 7000)'), ('guest_attending_reunion', 'Guest Attending Reunion (INR 5000)'), ('guest_attending_1st_day', 'Guest Attending 1st Day Full Function (INR 3500)'), ('guest_attending_2nd_day', 'Guest Attending 2nd Day Function (INR 1500)'), ('guest_attending_gala_dinner', 'Guest Attending only Gala Dinner (INR 2000)')], max_length=50),
        ),
    ]
