# Generated by Django 4.2.3 on 2023-07-19 06:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_registration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
