# Generated by Django 4.2.3 on 2023-07-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_registration_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='profession',
            field=models.CharField(choices=[('Businessman', 'Businessman'), ('Entrepreneur', 'Entrepreneur'), ('Doctor', 'Doctor'), ('Lawyer', 'Lawyer'), ('Engineer', 'Engineer'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
