# Generated by Django 4.2.3 on 2023-07-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_registration_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ManyToManyField(to='registration.event'),
        ),
    ]
