# Generated by Django 4.2.3 on 2023-07-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_event_remove_registration_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='attend_reunion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='attendees_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='members_attending_event',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Members Attending The Event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='passing_school',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of Passing School'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profession',
            field=models.CharField(blank=True, choices=[('Businessman', 'Businessman'), ('Entrepreneur', 'Entrepreneur'), ('Doctor', 'Doctor'), ('Lawyer', 'Lawyer'), ('Engineer', 'Engineer'), ('Others', 'Others')], default='Others', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL')], max_length=50, null=True, verbose_name='T-shirt Size'),
        ),
    ]
