# Generated by Django 4.2.3 on 2023-07-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_registration_file_alter_registration_attend_reunion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ManyToManyField(related_name='registration', to='registration.event'),
        ),
    ]
