# Generated by Django 4.2.3 on 2023-07-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_alter_registration_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ManyToManyField(blank=True, related_name='registration', to='registration.event'),
        ),
    ]
