# Generated by Django 4.2.3 on 2023-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_alter_registration_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
