# Generated by Django 4.2.3 on 2023-07-24 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_event_end_date_event_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_registration_last_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
