# Generated by Django 4.2.3 on 2023-07-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_event_event_registration_last_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.PositiveIntegerField(default='100'),
        ),
    ]
