# Generated by Django 4.2.3 on 2023-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_event_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='amount',
        ),
        migrations.AddField(
            model_name='event',
            name='is_this_main',
            field=models.BooleanField(default=False),
        ),
    ]
