# Generated by Django 4.2.3 on 2023-07-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0019_event_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
