# Generated by Django 4.2.3 on 2023-07-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='event',
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='registration.event'),
        ),
    ]
