# Generated by Django 4.2.3 on 2023-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0024_remove_payment_event_payment_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ManyToManyField(to='registration.event'),
        ),
    ]
