# Generated by Django 4.2.3 on 2023-07-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_remove_guest_event_guest_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='attendees_names',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='event',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_amt',
            field=models.PositiveIntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
