# Generated by Django 4.2.3 on 2023-07-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0026_remove_registration_attendees_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_data',
            new_name='payment_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='payment_transaction_id',
        ),
    ]
