# Generated by Django 4.2.3 on 2023-07-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_rename_razorpay_id_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='address',
        ),
    ]
