# Generated by Django 4.2.3 on 2023-07-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_remove_registration_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(default=342432, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_payment_id',
            field=models.CharField(default=234234, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='razorpay_signature_id',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
