# Generated by Django 4.2.3 on 2023-07-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_alter_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='file',
        ),
    ]
