# Generated by Django 4.2.3 on 2023-07-28 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_remove_registration_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='registration.registration'),
        ),
    ]
