# Generated by Django 4.2.3 on 2023-07-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_alter_payment_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_success',
            field=models.BooleanField(default=False),
        ),
    ]
