# Generated by Django 4.2.3 on 2023-07-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_alter_payment_payment_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='registration.event'),
        ),
    ]
