# Generated by Django 4.2.3 on 2023-08-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_registration_address_registration_anniversary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
