# Generated by Django 4.2.3 on 2023-08-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0039_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='has_joined',
            field=models.BooleanField(default=True, verbose_name='Has Joined'),
            preserve_default=False,
        ),
    ]
