# Generated by Django 4.2.3 on 2023-08-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_reference_has_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='has_joined',
            field=models.BooleanField(default=False, verbose_name='Has Joined'),
        ),
    ]
