# Generated by Django 4.2.5 on 2023-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0044_registration_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_amt',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_success',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_signature_id',
        ),
        migrations.AddField(
            model_name='registration',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='registration',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
