# Generated by Django 4.2.5 on 2023-10-05 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0045_rename_razorpay_order_id_payment_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='event',
        ),
        migrations.AlterField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(default=112, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='registration.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.event'),
        ),
    ]
