# Generated by Django 4.2.3 on 2024-01-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0046_remove_payment_event_alter_payment_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('registration', 'event'), name='reg-event'),
        ),
    ]
